server:
   port: 8080
   servlet:
      context-path: /silence
spring:
   application:
      name: silence
   profiles:
      active: dev
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/silence?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
   mail:
      host: smtp.163.com #发送邮件服务器
      username: soul_bay@163.com #QQ邮箱
      password: shizuka8989 #客户端授权码
      protocol: smtp #发送邮件协议
      properties.mail.smtp.auth: true
      properties.mail.smtp.port: 465 #端口号465或587
      properties.mail.display.sendmail: Javen #可以任意
      properties.mail.display.sendname: Spring Boot Guide Email #可以任意
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8
      from: soul_bay@163.com #与上面的username保持一致
   redis:
      spring.redis.database: 0 # Redis数据库索引（默认为0）
      spring.redis.host: localhost # Redis服务器地址
      spring.redis.port: 6379 # Redis服务器连接端口
      spring.redis.password: root # Redis服务器连接密码（默认为空）
      spring.redis.pool.max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      spring.redis.pool.max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      spring.redis.pool.max-idle: 8 # 连接池中的最大空闲连接
      spring.redis.pool.min-idle: 0 # 连接池中的最小空闲连接
      spring.redis.timeout: 1000 # 连接超时时间（毫秒）


mybatis:
   mapper-locations: classpath*:/mapper/**Mapper.xml,classpath*:/mapper/SilenceMapper/**Mapper.xml
   typeAliasesPackage: org.bobo.silence.bean
   configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
logging:
   file: silence.log
   level:
      com.test: debug